### ISSUE TITLE
Cannot build project

### ISSUE THREAD

**Issue by joseADA** [axoulc/Soundicode#1]
Hi, I am very interesting in testing your Soundicode app. 

I cloned the repository and imported it in Android Studio but I got several errors related to gradle SDK version and such. I finally couldn't manage to build and test the application due to gradle errors.

Could you please assist me on this issue? I am using Android Studio Flamingo on Windows 10.

Many thanks in advance!

**Comment by axoulc** [comment]
I'm glad you're interested in this project. It's been a while since I've put my nose into this project. I'll make sure to keep it up to date and keep finishing this project !
I'll keep you informed

**Comment by axoulc** [comment]
@joseADA I commit a new version with upgraded Gradle. From a stock version of Android Studio, it compiles. But music recognition algorithm is not working anymore. I'll try to fix that.

**Comment by joseADA** [comment]
Many thanks for the quick update! I am very interesting in music recognition, let's hope you can fix it. 

Best regards!

**Comment by Fl3xTr0n** [comment]
Hello axoulc, just so you know i'm also very interested in this project, i really hope you can fix it 👍

**Comment by axoulc** [comment]
Hi @joseADA @Fl3xTr0n,
I made some Gradle upgrade and from a fresh install of android studio, audio recognition works again.
Tell me if it's good for you. Async task for audio recording is very bad in terms of performance, I'll try to improve that.

**Comment by joseADA** [comment]
Hi again. It's good to hear good news. Thanks for the update! Regards.

**Comment by joseADA** [comment]
The project is buit now on Android Studio Flamingo.
P.S. There are errors on execution but that's another issue.
